
        
        name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
            server: ftpupload.net # 3.Change if using another host (ver de InfinityFree)
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            server-dir: /vmh.great-site.org/htdocs/ #4.Si SOLO UN dominio escribe /htdocs/ (con las dos diagonales) solamente
            retries: 3
            retryDelay: 10